import logging
from typing import Any
from src.observability.tracing import trace_step
from src.providers.embeddings.base import EmbeddingProvider
from src.providers.vector_store.base import VectorStore
import os
from dotenv import load_dotenv
load_dotenv()

logger = logging.getLogger(__name__)

class IndexingService:
    """
    Orchestrate document embedding and vector-store indexing.

    Embedding providers should only be responsible for converting text
    into vectors, while vector-store providers should only be responsible
    for storing and retrieving documents.This service coordinates those components and owns the ingestion
    workflow:

        chunks
            -> batch
            -> embeddings
            -> attach vectors
            -> vector store

    - Documents are processed in batches to reduce API overhead and avoid holding embeddings for the complete corpus in memory.
    - Existing deterministic chunk IDs allow the same documents to be uploaded again without generating new identifiers.
    - The service fails fast when a batch cannot be embedded or indexed. For a production ingestion platform, failed batches could instead
        be written to a retry queue or dead-letter store.

    Args:
        embedding_provider:
            Provider used to generate dense text embeddings.

        vector_store:
            Destination vector store used to persist embedded chunks.

        batch_size:
            Number of chunks embedded and uploaded per iteration.
    """

    def __init__(self, embedding_provider: EmbeddingProvider, vector_store: VectorStore, batch_size: int = int(os.getenv("BATCH_SIZE")),) -> None:

        if batch_size <= 0:
            raise ValueError(
                "batch_size must be greater than zero"
            )

        self.embedding_provider = embedding_provider
        self.vector_store = vector_store
        self.batch_size = batch_size

    def index_chunks(self, chunks: list[dict[str, Any]],) -> dict[str, int]:
        """
        Embed and index all supplied document chunks.

        Args:
            chunks:
                Chunk dictionaries generated by the chunking pipeline.

                Expected fields include:
                    - chunk_id
                    - text
                    - source
                    - page
                    - chunk_index
                    - token_count

        Returns:
            Summary dictionary containing:
                - total_chunks
                - indexed_chunks
                - batches

        Raises:
            ValueError:
                If the chunk collection is empty or required chunk fields
                are missing.

            RuntimeError:
                If embedding generation or vector-store indexing fails.
        """

        if not chunks:
            raise ValueError(
                "chunks must contain at least one document"
            )

        self._validate_chunks(chunks)

        total_chunks = len(chunks)
        indexed_chunks = 0
        batch_count = 0

        logger.info(
            "Starting full corpus indexing | "
            "chunks=%s | batch_size=%s",
            total_chunks,
            self.batch_size,
        )

        with trace_step("full_corpus_indexing"):

            for start in range(
                0,
                total_chunks,
                self.batch_size,
            ):
                end = min(
                    start + self.batch_size,
                    total_chunks,
                )

                batch = chunks[start:end]

                batch_count += 1

                logger.info(
                    "Processing indexing batch | "
                    "batch=%s | range=%s-%s | total=%s",
                    batch_count,
                    start + 1,
                    end,
                    total_chunks,
                )

                try:
                    embedded_batch = (
                        self._embed_batch(batch)
                    )

                    self.vector_store.add_documents(
                        embedded_batch
                    )

                except Exception as exc:
                    logger.exception(
                        "Indexing batch failed | "
                        "batch=%s | range=%s-%s",
                        batch_count,
                        start + 1,
                        end,
                    )

                    raise RuntimeError(
                        "Corpus indexing failed at "
                        f"batch {batch_count}"
                    ) from exc

                indexed_chunks += len(batch)

                logger.info(
                    "Indexing progress | "
                    "indexed=%s | total=%s",
                    indexed_chunks,
                    total_chunks,
                )

        logger.info(
            "Full corpus indexing completed | "
            "indexed=%s | batches=%s",
            indexed_chunks,
            batch_count,
        )

        return {
            "total_chunks": total_chunks,
            "indexed_chunks": indexed_chunks,
            "batches": batch_count,
        }

    def _embed_batch(self, chunks: list[dict[str, Any]],) -> list[dict[str, Any]]:
        """
        Generate embeddings and attach them to chunk metadata.

        Args:
            chunks:
                One indexing batch.

        Returns:
            New dictionaries containing the original chunk metadata plus
            an `embedding` field.

        Raises:
            RuntimeError:
                If the embedding provider returns a different number of
                vectors than input chunks.
        """

        texts = [
            chunk["text"]
            for chunk in chunks
        ]

        with trace_step("indexing_batch_embedding"):
            vectors = (self.embedding_provider.embed_texts(texts))

        if len(vectors) != len(chunks):
            raise RuntimeError(
                "Embedding count does not match "
                "chunk count"
            )

        return [
            {
                **chunk,
                "embedding": vector,
            }
            for chunk, vector in zip(
                chunks,
                vectors,
            )
        ]

    @staticmethod
    def _validate_chunks(chunks: list[dict[str, Any]],) -> None:
        """
        Validate minimum metadata required for indexing.

        Validation is performed before any external API calls so malformed
        chunks fail locally rather than midway through corpus ingestion.
        """

        required_fields = {
            "chunk_id",
            "text",
            "source",
            "page",
            "chunk_index",
            "token_count",
        }

        for position, chunk in enumerate(
            chunks,
            start=1,
        ):
            missing = (
                required_fields
                - chunk.keys()
            )

            if missing:
                raise ValueError(
                    f"Chunk {position} is missing "
                    f"required fields: "
                    f"{sorted(missing)}"
                )

            if not chunk["text"].strip():
                raise ValueError(
                    f"Chunk {position} contains "
                    "empty text"
                )