import logging
import os

from src.providers.vector_store.azure_search import (
    AzureAISearchVectorStore,
)
from src.providers.vector_store.base import (
    VectorStore,
)


logger = logging.getLogger(__name__)


def get_vector_store(
    embedding_dimension: int,
) -> VectorStore:
    """
    Create the configured vector-store provider.

    Why this factory exists:
        Provider selection is centralized so the RAG pipeline does not need
        vendor-specific conditional logic.

    Current provider:
        azure_search

    Future providers could include:
        - Qdrant
        - Pinecone
        - PostgreSQL/pgvector
        - Elasticsearch

    Args:
        embedding_dimension:
            Dimension generated by the configured embedding provider.

    Returns:
        Configured VectorStore implementation.

    Raises:
        ValueError:
            If VECTOR_STORE_PROVIDER references an unsupported provider.
    """

    provider_name = os.getenv(
        "VECTOR_STORE_PROVIDER",
        "azure_search",
    ).lower()

    logger.info(
        "Creating vector store | provider=%s",
        provider_name,
    )

    if provider_name == "azure_search":

        return AzureAISearchVectorStore(
            embedding_dimension=(
                embedding_dimension
            )
        )

    raise ValueError(
        f"Unsupported vector store provider: "
        f"{provider_name}"
    )